### ISSUE TITLE
Is it possible to change the colors of the output?

### ISSUE THREAD

**Issue by aravezskinteeth** [csgillespie/rprofile#14]
I used the example code and it's wonderful. I used to use a dracula theme for RStudio and the output and prompt was colorized with different colors like this:

<img width="711" alt="SCR-20230824-ooml" src="https://github.com/csgillespie/rprofile/assets/104392087/36e39b6d-1500-42df-94b2-145136985abf">

However, I found a `.rstheme` for [catppuccin](https://github.com/AngelBerihuete/rstudio/tree/main), however the multiple colors are gone and it shows only a red pastel color and I want them colorized like the draula one but with catppuccin colors:

<img width="715" alt="SCR-20230824-ooaw" src="https://github.com/csgillespie/rprofile/assets/104392087/6d729284-d71b-4b20-9309-a1f61c622a44">

Also, when I change to another theme included on RStudio, it shows those multiple colors. So maybe the issue is that maybe the coloring won't work on unofficial themes.

I wish I could manually change those colors, so I don't have to go back to dracula. However, I can't find any documentation on how to change colors anywhere.

**Comment by csgillespie** [comment]
Thanks for the report. Underneath, I just use https://github.com/gaborcsardi/prompt - could you try that package without my {rprofile}. If you still have a problem, then's file an issue with {prompt}. If not issue, then it looks like it's my fault :)

**Comment by aravezskinteeth** [comment]
Thank you for the suggestion. The issue seems to be with {prompt} it seems. I'll file an issue there.

> Thanks for the report. Underneath, I just use https://github.com/gaborcsardi/prompt - could you try that package without my {rprofile}. If you still have a problem, then's file an issue with {prompt}. If not issue, then it looks like it's my fault :)
