### ISSUE TITLE
mru file location error

### ISSUE THREAD

**Issue by jsta** [csgillespie/rprofile#4]
Maybe it's an OS or RStudio version difference but I am getting an error using `cp()`:

> Error in file(con, "r") : cannot open the connection
In addition: Warning message:
In file(con, "r") :
  cannot open file '/home/<user>/.rstudio-desktop/monitored/lists/project_mru': No such file or directory

My mru file is at `"~/.local/share/rstudio/monitored/lists/project_mru"`

```
> rstudioapi::versionInfo()$version
[1] ‘1.4.1100’
> devtools::session_info()
─ Session info ─────────────────────────────────────────────────────────────────────────
 setting  value                       
 version  R version 4.0.3 (2020-10-10)
 os       Ubuntu 20.04.1 LTS          
 system   x86_64, linux-gnu           
 ui       RStudio                     
 language (EN)                        
 collate  en_US.UTF-8                 
 ctype    en_US.UTF-8                 
 tz       America/New_York            
 date     2021-01-01 
```

**Comment by csgillespie** [comment]
Thanks!
