### ISSUE TITLE
Duplicate prompt initialization

### ISSUE THREAD

**Issue by mavam** [csgillespie/rprofile#6]
I'm trying to debug an issue where my terminal does not react properly after initializing. Looking at this function, why is a fancy prompt initialized on entry and an RStudio prompt before exit?

```R
set_terminal = function(rdoc = TRUE, colorout = TRUE, prettycode = TRUE) {
  prompt::set_prompt(prompt::prompt_fancy)
  if (isTRUE(prettycode)) prettycode::prettycode()
  if (isTRUE(rdoc)) {
    base::library("utils") # Needed for rdoc`?` to take precedence
    rdoc::use_rdoc()
  }

  if (isTRUE(colorout) && requireNamespace("colorout", quietly = TRUE)) {
      base::library("colorout")
  }
  prompt::set_prompt(rstudio_prompt)
}
```

Shouldn't the `rstudio_prompt` be loaded conditionally, only when RStudio is available?

**Comment by csgillespie** [comment]
You're sort of correct
1. It doesn't make sense to run  `prompt::set_prompt(rstudio_prompt)` as the prompt has already been run
2. It's not so much conditional, it shouldn't be there in the first place.

However, I don't think I like the fancy prompt. So I'll tweak the function to allow it to be passed as an argument.

---

When you say, doesn't react, what do you mean?

**Comment by mavam** [comment]
Yeah, making it an optional parameter seems more flexible. I wound up copying the function body in `.Rprofile` as a workaround

> When you say, doesn't react, what do you mean?

It looks like the RStudio prompt injects some non-printable ASCII control characters that mess up readline, rendering the CLI history search unusable.
